In [1]:
import torch
import torchvision
import torchaudio

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import torch.nn as nn

In [3]:
class linearRegression(nn.Module):
    def __init__(self, input_size, output_size):
        super(linearRegression, self).__init__()
        self.linear = nn.Linear(input_size, output_size)
    
    def forward(self, x):
        yhat = self.linear(x)
        return yhat
    
        
        

In [4]:
import pandas as pd

In [5]:
df = pd.read_csv("./seattle_airbnb_listings_cleaned.csv", na_values=[' '])
df

price  review_scores_rating  number_of_reviews  security_deposit  \
0      300                   100                 24               500   
1      149                    96                 11               300   
2       95                    95                 79               150   
3      105                   100                 13               500   
4      140                    99                 30               250   
..     ...                   ...                ...               ...   
334    250                    95                  4               250   
335    125                    95                 12               150   
336    100                    98                 10               200   
337    175                    96                 29               500   
338    154                    92                  5               150   

     cleaning_fee neighborhood property_type        room_type  accommodates  \
0              95  Wallingford         House  Entire home/apt             5   
1             105  Wallingford     Apartment  Entire home/apt             6   
2              40  Wallingford     Apartment  Entire home/apt             3   
3              50  Wallingford         House     Private room             2   
4              65  Wallingford         House  Entire home/apt             2   
..            ...          ...           ...              ...           ...   
334           100      Fremont         House  Entire home/apt            16   
335            45      Fremont     Apartment  Entire home/apt             2   
336            89      Fremont     Apartment  Entire home/apt             6   
337            95      Fremont         House  Entire home/apt             6   
338            85      Fremont         House  Entire home/apt             5   

     bathrooms  beds  host_response_time  host_response_rate  \
0          1.5     3  within a few hours                1.00   
1          1.0     3      within an hour                1.00   
2          1.0     2      within an hour                1.00   
3          2.0     1  within a few hours                1.00   
4          1.0     1      within an hour                1.00   
..         ...   ...                 ...                 ...   
334        3.5    10  within a few hours                0.97   
335        1.0     1  within a few hours                1.00   
336        1.0     2      within an hour                1.00   
337        2.0     3  within a few hours                1.00   
338        1.0     3      within an hour                1.00   

     host_acceptance_rate host_is_superhost host_has_profile_pic  \
0                       1                 t                    t   
1                       1                 f                    t   
2                       1                 f                    t   
3                       1                 t                    t   
4                       1                 t                    t   
..                    ...               ...                  ...   
334                     1                 f                    t   
335                     1                 t                    t   
336                     1                 f                    t   
337                     1                 f                    t   
338                     1                 f                    t   

    host_identity_verified  
0                        t  
1                        t  
2                        t  
3                        t  
4                        t  
..                     ...  
334                      t  
335                      t  
336                      t  
337                      t  
338                      t  

[339 rows x 17 columns]

In [6]:
df.dropna()

price  review_scores_rating  number_of_reviews  security_deposit  \
0      300                   100                 24               500   
1      149                    96                 11               300   
2       95                    95                 79               150   
3      105                   100                 13               500   
4      140                    99                 30               250   
..     ...                   ...                ...               ...   
334    250                    95                  4               250   
335    125                    95                 12               150   
336    100                    98                 10               200   
337    175                    96                 29               500   
338    154                    92                  5               150   

     cleaning_fee neighborhood property_type        room_type  accommodates  \
0              95  Wallingford         House  Entire home/apt             5   
1             105  Wallingford     Apartment  Entire home/apt             6   
2              40  Wallingford     Apartment  Entire home/apt             3   
3              50  Wallingford         House     Private room             2   
4              65  Wallingford         House  Entire home/apt             2   
..            ...          ...           ...              ...           ...   
334           100      Fremont         House  Entire home/apt            16   
335            45      Fremont     Apartment  Entire home/apt             2   
336            89      Fremont     Apartment  Entire home/apt             6   
337            95      Fremont         House  Entire home/apt             6   
338            85      Fremont         House  Entire home/apt             5   

     bathrooms  beds  host_response_time  host_response_rate  \
0          1.5     3  within a few hours                1.00   
1          1.0     3      within an hour                1.00   
2          1.0     2      within an hour                1.00   
3          2.0     1  within a few hours                1.00   
4          1.0     1      within an hour                1.00   
..         ...   ...                 ...                 ...   
334        3.5    10  within a few hours                0.97   
335        1.0     1  within a few hours                1.00   
336        1.0     2      within an hour                1.00   
337        2.0     3  within a few hours                1.00   
338        1.0     3      within an hour                1.00   

     host_acceptance_rate host_is_superhost host_has_profile_pic  \
0                       1                 t                    t   
1                       1                 f                    t   
2                       1                 f                    t   
3                       1                 t                    t   
4                       1                 t                    t   
..                    ...               ...                  ...   
334                     1                 f                    t   
335                     1                 t                    t   
336                     1                 f                    t   
337                     1                 f                    t   
338                     1                 f                    t   

    host_identity_verified  
0                        t  
1                        t  
2                        t  
3                        t  
4                        t  
..                     ...  
334                      t  
335                      t  
336                      t  
337                      t  
338                      t  

[339 rows x 17 columns]

In [7]:
df["price"].astype("float")
df["review_scores_rating"].astype("float")

0      100.0
1       96.0
2       95.0
3      100.0
4       99.0
       ...  
334     95.0
335     95.0
336     98.0
337     96.0
338     92.0
Name: review_scores_rating, Length: 339, dtype: float64

In [8]:
x = df["review_scores_rating"]
y = df["price"]
print(x.head())
print(y.head())

0    100
1     96
2     95
3    100
4     99
Name: review_scores_rating, dtype: int64
0    300
1    149
2     95
3    105
4    140
Name: price, dtype: int64


In [9]:
x = np.array(x).astype("float64")
y = np.array(y).astype("float64")
x[0]

100.0

In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state=123)

In [11]:
# Create Linear Regression Class

from torch import nn

class linear_regression(nn.Module):
    
    # Constructor
    def __init__(self, input_size, output_size):
        super(linear_regression, self).__init__()
        self.linear = nn.Linear(input_size, output_size)
    
    # Prediction function
    def forward(self, x):
        yhat = self.linear(x)
        return yhat

In [12]:
criterion = nn.MSELoss()

In [13]:
# Create Learning Rate list, the error lists and the MODELS list

learning_rates=[0.0001]

train_error=torch.zeros(len(learning_rates))
validation_error=torch.zeros(len(learning_rates))

MODELS=[]

In [14]:
# Define the train model function and train the model

def train_model_with_lr (iter, lr_list):
    
    # iterate through different learning rates 
    for i, lr in enumerate(lr_list):
        model = linear_regression(1, 1)
        optimizer = torch.optim.SGD(model.parameters(), lr = lr)
        for epoch in range(iter):
            for j in range(len(x_train)):
                xx = torch.from_numpy(np.array(x_train[j])).float()
                yy = torch.from_numpy(np.array(y_train[j])).float()
                xxx = xx.view(1, 1)
                yhat = model(xxx)
                loss = criterion(yhat, yy)
                optimizer.zero_grad()
                loss.backward()
                optimizer.step()
            for k in model.parameters():
                print(k)
        print("aaa")
                
        MODELS.append(model)

train_model_with_lr(100, learning_rates)

C:\Users\x2421\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\nn\modules\loss.py:535: UserWarning: Using a target size (torch.Size([])) that is different to the input size (torch.Size([1, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


Parameter containing:
tensor([[2.8877]], requires_grad=True)
Parameter containing:
tensor([0.7914], requires_grad=True)
Parameter containing:
tensor([[2.8878]], requires_grad=True)
Parameter containing:
tensor([0.7747], requires_grad=True)
Parameter containing:
tensor([[2.8880]], requires_grad=True)
Parameter containing:
tensor([0.7581], requires_grad=True)
Parameter containing:
tensor([[2.8882]], requires_grad=True)
Parameter containing:
tensor([0.7415], requires_grad=True)
Parameter containing:
tensor([[2.8883]], requires_grad=True)
Parameter containing:
tensor([0.7249], requires_grad=True)
Parameter containing:
tensor([[2.8885]], requires_grad=True)
Parameter containing:
tensor([0.7083], requires_grad=True)
Parameter containing:
tensor([[2.8887]], requires_grad=True)
Parameter containing:
tensor([0.6917], requires_grad=True)
Parameter containing:
tensor([[2.8888]], requires_grad=True)
Parameter containing:
tensor([0.6751], requires_grad=True)
Parameter containing:
tensor([[2.8890]],

In [15]:
learning_rate1 = 0.0001
criterion1 = nn.MSELoss()

In [16]:
model1 = linearRegression(1,1)
optimizer1 = torch.optim.SGD(model1.parameters(), lr = learning_rate1)
for i in range(100):
    for j in range(len(x_train)):
        xx = torch.from_numpy(np.array(x_train[j])).float()
        yy = torch.from_numpy(np.array(y_train[j])).float()
        xxx = xx.view(1, 1)
        yhat = model1(xxx)
        loss = criterion1(yhat, yy)
        optimizer1.zero_grad()
        loss.backward()
        optimizer1.step()
    for k in model1.parameters():
            print(k)

Parameter containing:
tensor([[2.9020]], requires_grad=True)
Parameter containing:
tensor([-0.6362], requires_grad=True)
Parameter containing:
tensor([[2.9022]], requires_grad=True)
Parameter containing:
tensor([-0.6523], requires_grad=True)
Parameter containing:
tensor([[2.9023]], requires_grad=True)
Parameter containing:
tensor([-0.6684], requires_grad=True)
Parameter containing:
tensor([[2.9025]], requires_grad=True)
Parameter containing:
tensor([-0.6846], requires_grad=True)
Parameter containing:
tensor([[2.9027]], requires_grad=True)
Parameter containing:
tensor([-0.7007], requires_grad=True)
Parameter containing:
tensor([[2.9028]], requires_grad=True)
Parameter containing:
tensor([-0.7168], requires_grad=True)
Parameter containing:
tensor([[2.9030]], requires_grad=True)
Parameter containing:
tensor([-0.7329], requires_grad=True)
Parameter containing:
tensor([[2.9032]], requires_grad=True)
Parameter containing:
tensor([-0.7490], requires_grad=True)
Parameter containing:
tensor([[2

In [17]:
for i in model1.parameters():
    print(i)

Parameter containing:
tensor([[2.9178]], requires_grad=True)
Parameter containing:
tensor([-2.2074], requires_grad=True)


In [27]:
error = []
e = 0
for i in range(len(x_test)):
    xx = torch.from_numpy(np.array(x_test[i])).float()
    xx = xx.view(1,1)
    yy = model1(xx)
    print(yy)
    error.append(float((yy-y_test[i])*(yy-y_test[i])))
#print(yy)
#print(y_train[1])
error = np.array(error)
error.mean()

tensor([[280.8227]], grad_fn=<AddmmBackward0>)
tensor([[272.0692]], grad_fn=<AddmmBackward0>)
tensor([[231.2195]], grad_fn=<AddmmBackward0>)
tensor([[239.9730]], grad_fn=<AddmmBackward0>)
tensor([[277.9049]], grad_fn=<AddmmBackward0>)
tensor([[274.9870]], grad_fn=<AddmmBackward0>)
tensor([[242.8908]], grad_fn=<AddmmBackward0>)
tensor([[277.9049]], grad_fn=<AddmmBackward0>)
tensor([[283.7405]], grad_fn=<AddmmBackward0>)
tensor([[280.8227]], grad_fn=<AddmmBackward0>)
tensor([[289.5762]], grad_fn=<AddmmBackward0>)
tensor([[272.0692]], grad_fn=<AddmmBackward0>)
tensor([[277.9049]], grad_fn=<AddmmBackward0>)
tensor([[280.8227]], grad_fn=<AddmmBackward0>)
tensor([[277.9049]], grad_fn=<AddmmBackward0>)
tensor([[277.9049]], grad_fn=<AddmmBackward0>)
tensor([[283.7405]], grad_fn=<AddmmBackward0>)
tensor([[283.7405]], grad_fn=<AddmmBackward0>)
tensor([[274.9870]], grad_fn=<AddmmBackward0>)
tensor([[260.3979]], grad_fn=<AddmmBackward0>)
tensor([[260.3979]], grad_fn=<AddmmBackward0>)
tensor([[289.

24705.545153673957

In [29]:
xx = torch.from_numpy(np.array(x_train[0])).float()
xx = xx.view(1,1)
print(xx)
yy = MODELS[0](xx)
print(yy)
print(y_train[1])

tensor([[95.]])
tensor([[275.0476]], grad_fn=<AddmmBackward0>)
99.0
